### ISSUE TITLE
unionfind unit test keeps failing

### ISSUE THREAD

**Issue by rotten** [maxdemarzi/graph_processing#3]
This test keeps failing when I try to build graph_processing.

[ Note that I built against 3.0.6 rather than 3.0.4, could that have made the difference? ]

```
-------------------------------------------------------------------------------
Test set: com.maxdemarzi.processing.UnionFindTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 21.67 sec <<< FAILURE!
shouldGetUnionFindMapStorage(com.maxdemarzi.processing.UnionFindTest)  Time elapsed: 10.811 sec  <<< FAILURE!
java.lang.AssertionError: expected:<2.0> but was:<1.0>
    at org.junit.Assert.fail(Assert.java:93)
    at org.junit.Assert.failNotEquals(Assert.java:647)
    at org.junit.Assert.assertEquals(Assert.java:443)
    at org.junit.Assert.assertEquals(Assert.java:512)
    at com.maxdemarzi.processing.UnionFindTest.shouldGetUnionFindMapStorage(UnionFindTest.java:56)

```

**Comment by rotten** [comment]
To get past it, I simply changed the 'EXPECTED' value, but I'm not sure if that was correct...
